name: Run R Script in Docker

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull and Run R Script Container
        run: |
          docker pull ghcr.io/${{ github.repository }}/r-script:latest
          docker run --rm ghcr.io/${{ github.repository }}/r-script:latest